### ISSUE TITLE
Using this plugin in 2024

### ISSUE THREAD

**Issue by nickwelp** [larsthorup/react-native-ble-plx-mock-recorder#2]
I found this slide show made by the author very helpful and think it should get a link in the Read Me - https://www.fullstackagile.eu/2021/09/02/react-native-bluetooth-ble-mock-recording/bluetooth-mock-recording-reactnativeeu-2021-09-02-publish.pdf

The react-native-ble-plx library itself is in a great state because it is now available as an Expo Plugin and very easy to work with. 

React-Native-ble-ple-mock-recorder, and supporting libraries react-native-ble-plx-mock-recorder-mocha-cli react-native-ble-plx-mock-recorder-mocha-core all work as intended.

A bigger challenge is BleRecorderApp, the App that is used to record the Ble Communications for the purpose of using the recordings in integration tests. I was able to get it working by creating a new Expo App, installing react-native-ble-plx, and then installing the libraries needed by reading the older app's Package.json (ignoring the older app's version numbers).  

I copied the /src files and some other stuff like .env from the older mobile app to the newer one and it works, and is recording 

I want to reiterate how helpful i found the slideshow and think it should be in the readme. Thanks for this helpful library!

Ultimately though I made the App with Expo, I started using the react-native commands from the older app's package.json, and copied all the "scripts" commands except 'ios', 'start' and 'lint'. All 'record' commands and their follow up steps work

**Comment by larsthorup** [comment]
Thank you @nickwelp for your detailed comments - happy you got it to work!

I have added the links to the slides and the video presentation: https://github.com/larsthorup/react-native-ble-plx-mock-recorder/commit/de3bf4f95081a6368b894661f6ca3233848fcd60
